### ISSUE TITLE
Panic error from Stick 0.11.1 if controller is connected via bluetooth.

### ISSUE THREAD

**Issue by Lite5h4dow** [libcala/stick#28]
**Describe the bug**
Getting ```thread 'main' panicked at 'Couldn't create inotify (2)!', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/stick-0.11.1/src/ffi/linux.rs:664:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
when running example code on raspian.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download example code
2. compile for RPI0
3. connect Xbox one controller over Bluetooth. 
4. execute on RPI0
5. See error

**Expected behavior**
Example code to run as expected

**Screenshots**
over bluetooth:
![image](https://user-images.githubusercontent.com/18059545/120384971-c23aca00-c31e-11eb-9752-94b0255e7421.png)
wired:
![image](https://user-images.githubusercontent.com/18059545/120385910-e4811780-c31f-11eb-8649-12a1abd9272f.png)
(application hangs here and no longer responds. see: [this](https://github.com/libcala/stick/issues/27) )

**Desktop (please complete the following information):**
 - Device: RPI0
 - OS: Raspian (ARM)

**Comment by AldaronLau** [comment]
@Lite5h4dow thanks!  So, this bug doesn't trigger if the controller is plugged in through USB?

**Comment by Lite5h4dow** [comment]
@AldaronLau that's right if it's plugged in there is no panic. Only if it is connected via Bluetooth

**Comment by Lite5h4dow** [comment]
any chance to look at this?

**Comment by AldaronLau** [comment]
@Lite5h4dow not yet

**Comment by Lite5h4dow** [comment]
@AldaronLau no chance to look at it yet?

**Comment by AldaronLau** [comment]
@Lite5h4dow still looking into how to reproduce the bug - I tried with a PS3 controller but my computer thinks it's a bluetooth keyboard, I might be able to get it to happen with a switch controller.

**Comment by AldaronLau** [comment]
@Lite5h4dow Can you try running this again, and see if either of #27 or this issue have been fixed?  I was able to successfully run stick on the Pi Zero W after making some changes, but I wasn't seeing the same errors you were.  Thanks!

**Comment by AldaronLau** [comment]
@Lite5h4dow Any chance to test this again?

**Comment by Lite5h4dow** [comment]
I'll give it a go tomorrow when I wake up

**Comment by Lite5h4dow** [comment]
still getting a panic when the controller is connected via Bluetooth
```
[bluetooth]# connect 9C:AA:1B:CE:15:E8 
Attempting to connect to 9C:AA:1B:CE:15:E8
[CHG] Device 9C:AA:1B:CE:15:E8 Connected: yes
[CHG] Device 9C:AA:1B:CE:15:E8 Modalias: usb:v045Ep02E0d0903
[CHG] Device 9C:AA:1B:CE:15:E8 Modalias: usb:v045Ep02FDd0903
[CHG] Device 9C:AA:1B:CE:15:E8 UUIDs: 00001124-0000-1000-8000-00805f9b34fb
[CHG] Device 9C:AA:1B:CE:15:E8 UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device 9C:AA:1B:CE:15:E8 ServicesResolved: yes
[CHG] Device 9C:AA:1B:CE:15:E8 Paired: yes
Connection successful
[Xbox Wireless Controller]# exit
pi@raspberrypi:~ $ ./Stick-test 
thread 'main' panicked at 'Couldn't add inotify watch!', /usr/stick/stick/src/sys/linux.rs:708:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pi@raspberrypi:~ $ ./Stick-test 
thread 'main' panicked at 'Couldn't add inotify watch!', /usr/stick/stick/src/sys/linux.rs:708:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AldaronLau** [comment]
@Lite5h4dow I unfortunately can't get any bluetooth connection because I only have PS3 and Switch controllers that are bluetooth compatible, and I can't get them to work at all under Linux.  So, I wish I could test and fix it, but I can't do it myself - so I'm going to add a help-wanted label.

**Comment by Lite5h4dow** [comment]
no worries. one thing i have noticed @AldaronLau , is this

wired:
```
pi@raspberrypi:~ $ ls /dev/input/
by-id  by-path  event0  js0  mice
```

Bluetooth:
```
pi@raspberrypi:~ $ ls /dev/input/
event0  event1  js0  mice
```

i don't know if that helps at all?

**Comment by Lite5h4dow** [comment]
it seems to be using event1 for the controller when connected via Bluetooth

**Comment by AldaronLau** [comment]
@Lite5h4dow Thanks!  That's interesting, so I guess the by-id and by-path directories can't be expected to exist.  I think how stick checks for new controllers needs to change, so that it checks all files that match `/dev/input/event*` to see if they are a joystick/gamepad/controller.

I should be able to change that without needing a bluetooth connection.

**Comment by Lite5h4dow** [comment]
ok, I did some research and yeah Bluetooth devices don't do the whole device by id and device by the path. doing some tinkering, I found that the controller actually is using event0 for its events and event1 I believe is for outgoing? (not 100% sure on that but it would seem to make sense. I found the following documentation. hopefully, I've done some of the leg work for you:

- Linux kernel documentation: https://www.kernel.org/doc/html/latest/input/input.html
- this one is specifically for RPI and python, but it also uses evdev bindings: https://raspberry-valley.azurewebsites.net/Map-Bluetooth-Controller-using-Python/

I haven't figured out how you're going to filter the gamepads and other controllers from mice and keyboards and other input peripherals. I know they have their own file types, so key0 and so on, however, if some unusual device acts as a controller it could throw it off...

**Comment by AldaronLau** [comment]
@Lite5h4dow thanks!

**Comment by AldaronLau** [comment]
@Lite5h4dow I have patched stick to get the controllers from /dev/input/ instead of /dev/input/by-id - everything seems to work the same as it did before with some minor tweaks I made.  Do you want to check to make sure it works?

**Comment by Lite5h4dow** [comment]
yup still works, but no bluetooth still...

**Comment by AldaronLau** [comment]
@Lite5h4dow have you tried the Python example in the [link you sent](https://raspberry-valley.azurewebsites.net/Map-Bluetooth-Controller-using-Python/), and does it work?

**Comment by Lite5h4dow** [comment]
i have, i even tried doing the evtest as recommended in the Linux documentation and got the following (over Bluetooth.)
```
pi@raspberrypi:~ $ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:      Xbox Wireless Controller
Select the device event number [0-0]: 0
Input driver version is 1.0.1
Input device ID: bus 0x5 vendor 0x45e product 0x2fd version 0x903
Input device name: "Xbox Wireless Controller"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 158 (KEY_BACK)
    Event code 172 (KEY_HOMEPAGE)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
    Event code 318 (BTN_THUMBR)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value  33422
      Min        0
      Max    65535
      Flat    4095
    Event code 1 (ABS_Y)
      Value  33575
      Min        0
      Max    65535
      Flat    4095
    Event code 2 (ABS_Z)
      Value  33346
      Min        0
      Max    65535
      Fuzz     255
      Flat    4095
    Event code 5 (ABS_RZ)
      Value  34016
      Min        0
      Max    65535
      Fuzz     255
      Flat    4095
    Event code 9 (ABS_GAS)
      Value      0
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 10 (ABS_BRAKE)
      Value      0
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 21 (EV_FF)
    Event code 80 (FF_RUMBLE)
    Event code 81 (FF_PERIODIC)
    Event code 88 (FF_SQUARE)
    Event code 89 (FF_TRIANGLE)
    Event code 90 (FF_SINE)
    Event code 96 (FF_GAIN)
Properties:
Testing ... (interrupt to exit)
Event: time 1625434196.503013, type 3 (EV_ABS), code 2 (ABS_Z), value 33299
Event: time 1625434196.503013, type 3 (EV_ABS), code 5 (ABS_RZ), value 32416
Event: time 1625434196.503013, -------------- SYN_REPORT ------------
```

**Comment by AldaronLau** [comment]
@Lite5h4dow I just modified the code to try opening as readonly, then as writeonly if opening as read/write fails.  I think that might be what was needed to make the bluetooth controller work, can you test the new main branch?

**Comment by AldaronLau** [comment]
@Lite5h4dow Any chance to see if the bluetooth controller works with the latest changes?

**Comment by Lite5h4dow** [comment]
hey man, sorry I havent gotten back to you sooner, I'm actually moving, hence why I haven't responded or tested yet. I don't get an internet connection and I don't unpack till Wednesday. so it looks like I won't get the chance to test till then. sorry!

**Comment by AldaronLau** [comment]
@Lite5h4dow No worries, sounds good!

**Comment by Lite5h4dow** [comment]
ok, ill be able to test this tonight
sorry it took so long only got internet installed a few days ago so everything is taking longer than xexpected. but i should be good to get back to you on this tonight

**Comment by Lite5h4dow** [comment]
no panic, but still no luck with getting it to read a controller

**Comment by Lite5h4dow** [comment]
SUCCESS!!!! we have Bluetooth input! 10/10 my man
