### ISSUE TITLE
Unknown Linux Button 158

### ISSUE THREAD

**Issue by Lite5h4dow** [libcala/stick#35]
**Describe the bug**
looks like the screenshare button on the box one controller isn't mapped.

**To Reproduce**
1. connect xbox one controller
2. start software
3. press snapshot button (bottom left of the box logo)
4. unknown linux button error

![image](https://user-images.githubusercontent.com/18059545/127892529-f61e5965-1b8a-42c1-bc67-edabf661c037.png)

**Expected behavior**
should be mapped as MenuL

**Screenshots**
![image](https://user-images.githubusercontent.com/18059545/127892580-151d1f67-0b38-474e-a3a4-13929976b3ef.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by AldaronLau** [comment]
@Lite5h4dow Thanks!  Fixed in 0.12.1, just released - so closing.
