### ISSUE TITLE
Are there any ways to get all connected gamepads?

### ISSUE THREAD

**Issue by DuckerMan** [libcala/stick#7]

**Comment by AldaronLau** [comment]
Yeah, the following program will make a `Vec` of all connected gamepads, and print out their names and ids:

```rust
use pasts::prelude::*;
use stick::{Event, Gamepad, Port};

async fn event_loop() {
    let mut port = Port::new();
    let mut gamepads = Vec::<Gamepad>::new();
    'e: loop {
        match port.fut().await {
            (_, Event::Connect(gamepad)) => {
                println!(
                    "Connected p{}, id: {:X}, name: {}",
                    gamepads.len() + 1,
                    gamepad.id(),
                    gamepad.name(),
                );
                gamepads.push(*gamepad);
            }
           _ => {}
        }
    }
}

fn main() {
    pasts::ThreadInterrupt::block_on(event_loop())
}
```

Is that what you were looking for?  I suppose one thing this can't do, is break out of the loop after all gamepads have been added to the `Vec`.  Do you think that would be a useful feature?

**Comment by DuckerMan** [comment]
It's weird, but `stick` can't find my `DirectInput` gamepad

**Comment by AldaronLau** [comment]
`stick` looks in /dev/input/by-id/ for files ending in "-event-joystick".  When I plug in an XBox controller the following files appear:

> /dev/input/event15
> /dev/input/js0
> /dev/input/by-id/usb-Performance_Designed_Products_Wired_Controller_for_Xbox_360_069CAAEF-event-joystick
> /dev/input/by-id/usb-Performance_Designed_Products_Wired_Controller_for_Xbox_360_069CAAEF-joystick
> /dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-event-joystick
> /dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick

Other people have reported `stick` not being able to see their controller, so I'd like to fix it.  I think the most useful thing for me to fix it would be an ls of /dev/input, /dev/input/by-id and /dev/input/by-path before and after plugging in your DirectInput gamepad.

**Comment by DuckerMan** [comment]
@AldaronLau  Hi, thanks for late reply! My OS is Windows, not a `Linux` one.

**Comment by DuckerMan** [comment]
It can't find both of DInput(`Maxfire Grandias 12V`) and XInput(`X360 controller`)

**Comment by AldaronLau** [comment]
@DuckerMan stick doesn't support Windows yet, but I already made an issue for it: https://github.com/libcala/stick/issues/1!  The reason it compiles is because it's using a "dummy" implementation that does nothing.  Hopefully, I can get it working soon!  Closing, unless you think it should be open for another reason.

**Comment by DuckerMan** [comment]
Thank you!
